name: Self-Hosted Runner CI/CD
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS-CLI
        uses: chrislennon/action-aws-cli@v1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: aws s3 sync ./github.com/Raghavjeet123/Raghav-s-Portfolio s3://raghav-dev
